name: Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/camc314/gh_actions_test/commits/${{ github.sha }} > commit.json

          commit_message=$(cat commit.json | jq -r '.commit.message')
          # Basic Comment
          echo "Commit message: $commit_message"

          current_sha=$(echo $commit_message | sed 's/.*Merge \([^ ]*\) into \([^ ]*\).*/\1/')
          target_sha=$(echo $commit_message | sed 's/.*Merge \([^ ]*\) into \([^ ]*\).*/\2/')
          echo "Current SHA: $current_sha"
          echo "Target SHA: $target_sha"

          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/camc314/gh_actions_test/commits/$target_sha > target_sha_commit.json

          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/camc314/gh_actions_test/commits/$current_sha > current_sha_commit.json

          echo $( cat current_sha_commit.json | jq -r '.commit.message' )
          echo $( cat target_sha_commit.json | jq -r '.commit.message' )

          # Format to String
          # Build updated at <CURRENT_DATE_TIME> from [Current SHA MESSAGE](<CURRENT_SHA_URL>) to [Target SHA MESSAGE](<TARGET_SHA_URL>)
          # Build is available at <BUILD_URL>

          # https://www.github.com/<OWNER>/<REPO>/commit/<SHA>
          current_sha_url="https://www.github.com/camc314/gh_actions_test/commit/$current_sha"
          target_sha_url="https://www.github.com/camc314/gh_actions_test/commit/$target_sha"

          echo "Build updated at $(date) from [$(cat current_sha_commit.json | jq -r '.commit.message')]($current_sha_url) to [$(cat target_sha_commit.json | jq -r '.commit.message')]($target_sha_url) \n Build is available at <BUILD_URL>"
          

