name: Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <YOUR-TOKEN>"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/openfin/workspace/commits/${{ github.head.sha }}



          echo ${{ github.head.sha }}
          # get info for the commit that triggered the workflow
          git log -1 ${{ github.head.sha }}
          # log github context + stringify it
          echo ${{ toJSON(github) }}
          # echo the commit sha
          echo ${{ github.sha }}
          # echo the commit message
          echo ${{ github.event.head_commit.message }}
          # echo the commit author
          echo ${{ github.event.head_commit.author.name }}
          # echo the commit time
          echo ${{ github.event.head_commit.timestamp }}
          #echo the current time
          echo $(date)
