name: Test Workflow2

on:
    pull_request:
        branches:
            - main

jobs:
    validate_cherry_pick:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Main Branch
              uses: actions/checkout@v3

            - name: Setup Node.js Environment validate
              uses: actions/setup-node@v3
              with:
                  cache: "npm"
                  node-version: 16
                  always-auth: true
                  registry-url: "https://registry.npmjs.org"

            - name: Install Dependencies
              run: npm i

            - name: Check PR labels and branch existence
              id: check_labels_branch
              #   # join with newline
              run: |
                  #   label="MERGE\nrelease/dubai"
                  #   IFS="," read -ra LABELS <<< "${{ join(github.event.pull_request.labels.*.name, ',') }}"
                  #   joined_labels=$(IFS=$'\n'; echo "${LABELS[*]}")
                  #   echo "LABELS=$joined_labels" >> $GITHUB_ENV
                  #   echo ${{ github.event.pull_request.labels.*.name }}

                  # echo github.event.pull_request.labels.*.name to json
                  #   echo ${{ toJson(github.event.pull_request.labels.*.name) }}
                  label=${{ toJson(github.event.pull_request.labels.*.name) }}


                  echo Hello
                  echo Hello
                  echo Hello

                  echo $label|node ./chx.js workspace ${{ secrets.GITHUB_TOKEN }}
                  result=$(echo $label|node ./chx.js workspace ${{ secrets.GITHUB_TOKEN }} )
                  echo "$result"

                  if [[ $result == "Success" ]]; then
                    echo "targetBranchExists=true" >> $GITHUB_OUTPUT
                    echo "targetBranchName=$label" >> $GITHUB_OUTPUT
                    echo "commitId=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_OUTPUT
                  else
                    echo "targetBranchExists=false" >> $GITHUB_OUTPUT
                  fi
